"""initial db setup

Revision ID: 1ca4e015e7b7
Revises: 
Create Date: 2023-08-20 07:28:01.648800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca4e015e7b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbversion', sa.String(length=20), nullable=True),
    sa.Column('sitename', sa.String(length=20), nullable=True),
    sa.Column('signup', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=110), nullable=True),
    sa.Column('active', sa.String(length=1), nullable=True),
    sa.Column('admin', sa.String(length=1), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pictures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('desc', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('userid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('users')
    op.drop_table('settings')
    # ### end Alembic commands ###
